name: pipeseq_env
dependencies:
- python =3.11
- pip:
  - snakemake==8.27.1
  - snakemake-executor-plugin-cluster-generic
  - cutadapt==5
  - countess==0.0.83
  - jupyterlab
  - pandas
  - matplotlib
  - numpy
  - seaborn
