name: pipeseq_env
dependencies:
- python =3.12
- pip:
  - snakemake==8.28.0
  - snakemake-executor-plugin-cluster-generic
  - cutadapt==5
  - countess==0.0.84
  - jupyterlab
  - pandas
  - matplotlib
  - numpy
  - seaborn
